config/routes.rb
Rails.application.routes.draw do
  resources :meetings
 root "index#index"
 resources :contacts
#  get 'contacts/new' => 'contacts#new'
#  post'contacts/create' => 'contacts#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :message, presence: true
  validates :email, presence: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  
  def index 
    @meetings = Meeting.all
  end

  def show
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/contacts/create.html.haml
.container
  .py-5.text-center
    = image_tag 'cap.jpg', class: "col-6 h-50"
    %h2 送信完了しました！
    %p.lead お問合せありがとうございました。(龍風一同)
    %button.btn.btn-default{:onclick => "location.href='/'", :type => "button"} 戻る
  

app/views/contacts/new.html.haml
= form_for @contact, url: contacts_path do |f|
  .form-group.mt-3
    %p.mb-0 返信先メールアドレス
    = f.text_field :email, class: 'form-control'
    - if @contact.errors.any?
      %i 正しいメールアドレスを入力してくださいませ!
  .form-group
    %p.mb-0 お問い合わせ内容 
    %p.mb-0※お名前の記入をお忘れなく！
    = f.text_area :message, size: '10x10', class: 'form-control'
  .submit.d-flex.justify-content-center
    = f.submit "送信", class: 'btn btn-default' 

app/views/index/_all-member.html.haml
.row.m-0 
  #player1.col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'raiki.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 1
      .col-6
        %strong.font-09 投手 / 右右  / 19歳
        %strong.h4.mt-2.name.d-block RAIKI
        %span.font-07.text-muted.d-block 切込隊長 /  ムードメーカー
        %span.font-07.text-muted.d-block 安南中(安城シニア)→誉高校
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'syuji.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 2
      .col-6
        %strong.font-09 捕手 / 右右  / 19歳
        %strong.h4.mt-2.name.d-block 西尾柊二
        %span.font-07.text-muted.d-block  強肩イップス
        %span.font-07.text-muted.d-block 安南中→安城学園→愛知学院大
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 3
      .col-6
        %strong.font-09 内野手 / 右右  / 45歳
        %strong.h4.mt-2.name.d-block 竹中大輔
        %span.font-07.text-muted.d-block 
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 4
      .col-6
        %strong.font-09 内野手 / 右右  / 32歳
        %strong.h4.mt-2.name.d-block ともぴ
        %span.font-07.text-muted.d-block  ホームラン王 / 顔面凶器 / 愛妻家
        %span.font-07.text-muted.d-block 朝日中(衣浦シニア) →岐阜中京
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 5
      .col-6
        %strong.font-09 内野手 / 右右  / 20歳
        %strong.h4.mt-2.name.d-block なおき
        %span.font-07.text-muted.d-block フルスイング / トンネル王子
        %span.font-07.text-muted.d-block 安南中(テニス部)→安城南(テニス部)→大同大
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 7
      .col-6
        %strong.font-09 内野手 / 右右  / 33歳
        %strong.h4.mt-2.name.d-block 板倉良介
        %span.font-07.text-muted.d-block 介護士 
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 10
      .col-6
        %strong.font-09 投手 / 右右  / 25歳
        %strong.h4.mt-2.name.d-block キャプテン
        %span.font-07.text-muted.d-block ニヤニヤ王子 / 釣り / エンジニア
        %span.font-07.text-muted.d-block 安南中→安城東→南山大(ソフトボール部)
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 15
      .col-6
        %strong.font-09 内野手 / 右右  / 29歳
        %strong.h4.mt-2.name.d-block 渡辺良弥
        %span.font-07.text-muted.d-block 
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 21
      .col-6
        %strong.font-09 内野手 / 右右  / 30歳
        %strong.h4.mt-2.name.d-block いっちー
        %span.font-07.text-muted.d-block 庶務 /  経理 / 記録係
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 25
      .col-6
        %strong.font-09 外野手 / 右右  / 26歳
        %strong.h4.mt-2.name.d-block 山口晋太郎
        %span.font-07.text-muted.d-block 柔道整復師
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'aoki.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 27
      .col-6
        %strong.font-09 外野手 / 右右  / 20歳
        %strong.h4.mt-2.name.d-block 青木達也
        %span.font-07.text-muted.d-block 
        %span.font-07.text-muted.d-block 安南中→安城高校→愛知淑徳大
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'D.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 29
      .col-6
        %strong.font-09 捕手 / 右左  / 33歳
        %strong.h4.mt-2.name.d-block 鈴木啓介
        %span.font-07.text-muted.d-block コーチ / お米屋さん
        %span.font-07.text-muted.d-block 田舎中→変態高→基地外大
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'tsune.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 30
      .col-6
        %strong.font-09 内野手 / 右右  / 40歳
        %strong.h4.mt-2.name.d-block ツネさん
        %span.font-07.text-muted.d-block 監督 / スカウト / 氣愛守備 /  愛煙家 / 恐妻家
        %span.font-07.text-muted.d-block 安北中(サッカー部)→?高校(3日で中退)
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 66
      .col-6
        %strong.font-09 外野手 / 左左  / 29歳
        %strong.h4.mt-2.name.d-block 板倉尉之
        %span.font-07.text-muted.d-block  料理長
        %span.font-07.text-muted.d-block
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'hyodou.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 77
      .col-6
        %strong.font-09 内野手 / 右左  / 19歳
        %strong.h4.mt-2.name.d-block 兵藤亮太
        %span.font-07.text-muted.d-block 首位打者
        %span.font-07.text-muted.d-block 安南中→安城学園
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 88
      .col-6
        %strong.font-09 外野手 / 右右  / 33歳
        %strong.h4.mt-2.name.d-block 下地慶昇
        %span.font-07.text-muted.d-block  にんじんしりしり 
        %span.font-07.text-muted.d-block 
  
 
 

app/views/index/_calendar.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "ie=edge", "http-equiv" => "X-UA-Compatible"}/
    %title Calendar
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat:400,600,700", :rel => "stylesheet"}/
    %link{:href => "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css", :rel => "stylesheet"}/
  %body
    .main-container-wrapper
      %main
        .calendar-container
          .calendar-container__header
            %button.calendar-container__btn.calendar-container__btn--left{:title => "Previous"}
              %i.icon.ion-ios-arrow-back
            %h2.calendar-container__title October 2018
            %button.calendar-container__btn.calendar-container__btn--right{:title => "Next"}
              %i.icon.ion-ios-arrow-forward
          .calendar-container__body
            .calendar-table
              .calendar-table__header
                .calendar-table__row
                  .calendar-table__col S
                  .calendar-table__col M
                  .calendar-table__col T
                  .calendar-table__col W
                  .calendar-table__col T
                  .calendar-table__col F
                  .calendar-table__col S
              .calendar-table__body
                .calendar-table__row
                  .calendar-table__col.calendar-table__inactive
                    .calendar-table__item
                      %span 30
                  .calendar-table__col.calendar-table__today
                    .calendar-table__item
                      %span 1
                  .calendar-table__col
                    .calendar-table__item
                      %span 2
                  .calendar-table__col
                    .calendar-table__item
                      %span 3
                  .calendar-table__col
                    .calendar-table__item
                      %span 4
                  .calendar-table__col.calendar-table__event
                    .calendar-table__item
                      %span 5
                  .calendar-table__col
                    .calendar-table__item
                      %span 6
                .calendar-table__row
                  .calendar-table__col.calendar-table__event
                    .calendar-table__item
                      %span 7
                  .calendar-table__col
                    .calendar-table__item
                      %span 8
                  .calendar-table__col
                    .calendar-table__item
                      %span 9
                  .calendar-table__col
                    .calendar-table__item
                      %span 10
                  .calendar-table__col
                    .calendar-table__item
                      %span 11
                  .calendar-table__col
                    .calendar-table__item
                      %span 12
                  .calendar-table__col
                    .calendar-table__item
                      %span 13
                .calendar-table__row
                  .calendar-table__col
                    .calendar-table__item
                      %span 14
                  .calendar-table__col
                    .calendar-table__item
                      %span 15
                  .calendar-table__col.calendar-table__event.calendar-table__event--long.calendar-table__event--start
                    .calendar-table__item
                      %span 16
                  .calendar-table__col.calendar-table__event.calendar-table__event--long
                    .calendar-table__item
                      %span 17
                  .calendar-table__col.calendar-table__event.calendar-table__event--long.calendar-table__event--end
                    .calendar-table__item
                      %span 18
                  .calendar-table__col
                    .calendar-table__item
                      %span 19
                  .calendar-table__col
                    .calendar-table__item
                      %span 20
                .calendar-table__row
                  .calendar-table__col
                    .calendar-table__item
                      %span 21
                  .calendar-table__col
                    .calendar-table__item
                      %span 22
                  .calendar-table__col
                    .calendar-table__item
                      %span 23
                  .calendar-table__col
                    .calendar-table__item
                      %span 24
                  .calendar-table__col
                    .calendar-table__item
                      %span 25
                  .calendar-table__col
                    .calendar-table__item
                      %span 26
                  .calendar-table__col.calendar-table__event.calendar-table__event--long.calendar-table__event--start
                    .calendar-table__item
                      %span 27
                .calendar-table__row
                  .calendar-table__col.calendar-table__event.calendar-table__event--long.calendar-table__event--end
                    .calendar-table__item
                      %span 28
                  .calendar-table__col
                    .calendar-table__item
                      %span 29
                  .calendar-table__col
                    .calendar-table__item
                      %span 30
                  .calendar-table__col
                    .calendar-table__item
                      %span 31
                  .calendar-table__col.calendar-table__event.calendar-table__inactive
                    .calendar-table__item
                      %span 1
                  .calendar-table__col.calendar-table__inactive
                    .calendar-table__item
                      %span 2
                  .calendar-table__col.calendar-table__inactive
                    .calendar-table__item
                      %span 3
        .events-container
          %span.events__title 今月の予定
          %ul.events__list
            %li.events__item
              .events__item--left
                %span.events__name Town hall meeting
                %span.events__date Oct 5
              %span.events__tag 16:00
            %li.events__item
              .events__item--left
                %span.events__name Meet with George
                %span.events__date Oct 7
              %span.events__tag 10:00
            %li.events__item
              .events__item--left
                %span.events__name Vacation!!!
                %span.events__date Oct 16 - Oct 18
              %span.events__tag.events__tag--highlighted All day
            %li.events__item
              .events__item--left
                %span.events__name Visit Grandma
                %span.events__date Oct 27 - Oct 28

app/views/index/_footer.html.haml
.footer.nav-scroller 
  .text-light.text-center© 2019 Rompuu.com All rights reserved.

app/views/index/_header.html.haml
.header
  .container
    .row.blog-header.d-flex.align-items-center.justify-content-between.ml-mb-5.mr-mb-5
      .R-logo.col-2 R
      .col-xs-4.rompuu-logo.text-light.d-flex.align-items-end
        .com.text-light rompuu.com
        .registration ™
  .navbar.mlb-font.d-inlineflex.justify-content-around
    %a.text-light{:href => "/"} Top
    %a.text-light{:href => "#"} Album
    %a.text-light{:href => "#"} Team
    %a.text-light{:href => "#"} Stats
    %a.text-light{:href => "/contacts/new"} Contact

app/views/index/_infielder.html.haml
.row.m-0
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 2
      .col-6
        %strong.font-09 捕手 / 右右  / 19歳
        %strong.h4.mt-2.name.d-block 西尾柊二
        %span.font-07.text-muted.d-block  強肩イップス
        %span.font-07.text-muted.d-block 安南中→安城学園
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 3
      .col-6
        %strong.font-09 内野手 / 右右  / 45歳
        %strong.h4.mt-2.name.d-block 竹中大輔
        %span.font-07.text-muted.d-block 
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 4
      .col-6
        %strong.font-09 内野手 / 右右  / 32歳
        %strong.h4.mt-2.name.d-block ともぴ
        %span.font-07.text-muted.d-block  ホームラン王 / 顔面凶器 / 愛妻家
        %span.font-07.text-muted.d-block 安南中(衣浦シニア) →岐阜中京
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 5
      .col-6
        %strong.font-09 内野手 / 右右  / 20歳
        %strong.h4.mt-2.name.d-block なおき
        %span.font-07.text-muted.d-block フルスイング / トンネル王子
        %span.font-07.text-muted.d-block 安南中(テニス部)→安城南(テニス部)→大同大
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 7
      .col-6
        %strong.font-09 内野手 / 右右  / 33歳
        %strong.h4.mt-2.name.d-block 板倉良介
        %span.font-07.text-muted.d-block 
        %span.font-07.text-muted.d-block   
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 15
      .col-6
        %strong.font-09 内野手 / 右右  / 29歳
        %strong.h4.mt-2.name.d-block 渡辺良弥
        %span.font-07.text-muted.d-block 
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 21
      .col-6
        %strong.font-09 内野手 / 右右  / 30歳
        %strong.h4.mt-2.name.d-block いっちー
        %span.font-07.text-muted.d-block 庶務 /  経理 / 記録係
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 29
      .col-6
        %strong.font-09 捕手 / 右左  / 33歳
        %strong.h4.mt-2.name.d-block D
        %span.font-07.text-muted.d-block コーチ / お米屋さん 
        %span.font-07.text-muted.d-block 田舎中→変態高→基地外大
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 30
      .col-6
        %strong.font-09 内野手 / 右右  / 40歳
        %strong.h4.mt-2.name.d-block ツネさん
        %span.font-07.text-muted.d-block 監督 / スカウト / 氣愛守備 / 愛煙家 / 恐妻家
        %span.font-07.text-muted.d-block 安北中(サッカー部)→3日で高校中退
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 77
      .col-6
        %strong.font-09 内野手 / 右左  / 19歳
        %strong.h4.mt-2.name.d-block 兵藤亮太
        %span.font-07.text-muted.d-block 
        %span.font-07.text-muted.d-block 安南中→安城学園

app/views/index/_outfielder.html.haml
.row.m-0
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 27
      .col-6
        %strong.font-09 外野手 / 右右  / 40歳
        %strong.h4.mt-2.name.d-block 青木達也
        %span.font-07.text-muted.d-block 監督 / スカウト 
        %span.font-07.text-muted.d-block 安北中(サッカー部)
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 25
      .col-6
        %strong.font-09 外野手 / 右右  / 26歳
        %strong.h4.mt-2.name.d-block 山口晋太郎
        %span.font-07.text-muted.d-block 柔道整復師
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 66
      .col-6
        %strong.font-09 外野手 / 左左  / 29歳
        %strong.h4.mt-2.name.d-block 板倉尉之
        %span.font-07.text-muted.d-block  料理長
        %span.font-07.text-muted.d-block 安南中→安城学園
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 88
      .col-6
        %strong.font-09 外野手 / 右右  / 33歳
        %strong.h4.mt-2.name.d-block 下地慶昇
        %span.font-07.text-muted.d-block  にんじんしりしり 
        %span.font-07.text-muted.d-block 

app/views/index/_pitcher.html.haml
.row.m-0
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 1
      .col-6
        %strong.font-09 投手 / 右右  / 19歳
        %strong.h4.mt-2.name.d-block RAIKI
        %span.font-07.text-muted.d-block 切込隊長 /  ムードメーカー
        %span.font-07.text-muted.d-block 安南中(安城シニア)→誉高校
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 10
      .col-6
        %strong.font-09 投手 / 右右  / 25歳
        %strong.h4.mt-2.name.d-block キャプテン
        %span.font-07.text-muted.d-block キャプテン / 釣り /  エンジニア
        %span.font-07.text-muted.d-block 安南中→安城東→南山大(ソフトボール部)

app/views/index/_supporters.html.haml
.row.m-0
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 
      .col-6
        %strong.font-09  撮影係 / 右右  
        %strong.h4.mt-2.name.d-block かほりん
        %span.font-07.text-muted.d-block 格闘家 /マッサージ師
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'R-logo.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 
      .col-6
        %strong.font-09  スコアラー / 右左
        %strong.h4.mt-2.name.d-block あーちゃん
        %span.font-07.text-muted.d-block 格闘家 / 保育士さん
        %span.font-07.text-muted.d-block 
  .col-md-6
    .row.align-items-center.border-bottom.p-2
      = image_tag 'ayu.jpg', class: "col-4"
      .col-2.player-num.h1.text-narrow.p-0.text-center 
      .col-6
        %strong.font-09  マネージャー / 右右
        %strong.h4.mt-2.name.d-block あゆちゃん
        %span.font-07.text-muted.d-block  保育士の卵ちゃん
        %span.font-07.text-muted.d-block 

app/views/meetings/edit.html.haml
%h1 Editing meeting

= render 'form'

= link_to 'Show', @meeting
\|
= link_to 'Back', meetings_path

app/views/meetings/index.html.haml
= month_calendar do |date|
  = date

app/views/meetings/new.html.haml
%h1 New meeting

= render 'form'

= link_to 'Back', meetings_path

app/views/meetings/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @meeting.name
%p
  %b Start time:
  = @meeting.start_time

= link_to 'Edit', edit_meeting_path(@meeting)
\|
= link_to 'Back', meetings_path